name: Run a sample test on github 

on:            
  push:        
    branches:  
      - master   
  workflow_dispatch:
    inputs:                    

      environment:               
        description: 'Which environment to test?'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - producti  on

      browser:                  
        description: 'Which browser?'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs: 
  test: 
    name: sample first test CICD execution 
    runs-on: windows-latest
    environment: BASEURL 
    steps:
      - name: Download the current project code  
        uses: actions/checkout@v3 

      - name: Download the environment (Nodejs) 
        uses: actions/setup-node@v3  
                                         
        with:
          node-version: '18'
          
      - name: install playwright  
        run: npm ci    

      - name: install the browsers of playwright and installthe libraries for that OS like graphis, styles..
        run: npx playwright install --with-deps   

      - name: Run/execute the tests 
        run: npx playwright test   
        env:
          PROD_URL: ${{ secrets.PROD_URL }}   
      - name: Upload reports after excution  
        uses:  actions/upload-artifact@v4 
        if: always() 
        with: 
          name: github-report 
          path: playwright-report/

     